
[window]
dynamic_padding = true
opacity = 0.95
blur = true

[scrolling]
history = 100000
multiplier = 1

[font]
normal = { family = "Terminess Nerd Font", style = "Regular" }
size = 6.5

[keyboard]
bindings = [
	{ key = "I", mods = "Control", chars = "\u001B[105;5u" }
]

[general]
import = [
    "~/.config/alacritty/themes/themes/carbonfox.toml"
]
