
[window]
dynamic_padding = true
opacity = 0.95
blur = true

[scrolling]
history = 100000
multiplier = 1

[font]
normal = { family = "JetBrainsMono Nerd Font Propo", style = "Regular" }
size = 11.5

[general]
import = [
    "~/.config/alacritty/themes/themes/carbonfox.toml"
]
