
[window]
dynamic_padding = true
opacity = 0.75
blur = true

[scrolling]
history = 100000
multiplier = 1

[font]
normal = { family = "JetBrainsMono Nerd Font Propo", style = "Regular" }
size = 10

[general]
import = [
    "~/.cache/wal/colors-alacritty.toml"
]
